console.log("Addition of Numbers 6 and 2 is ");
console.log(6 + "+" + 2 + "=");
console.log(6 + 2);
console.log("Subtraction of Numbers 10 and 2 is ");
console.log(10 + "-" + 2 + "=");
console.log(10 - 2);
console.log("Multiplication of Numbers 4 and 2 is ");
console.log(4 + "*" + 2 + "=");
console.log(4 * 2);
console.log("Division of Numbers 16 and 2 is ");
console.log(16 + "/" + 2 + "=");
console.log(16 / 2);
