var myName = "Malik";
console.log("Is myName=='Malik'? | Predict True.");
console.log(myName == "Malik");
console.log("Is myName=='Junaid'? | Predict False.");
console.log(myName == "Junaid");
console.log("Is myName.length ==5? | Predict True.");
console.log(myName.length == 5);
console.log("myName.charAt(1)=='Z' ? | Predict False.");
console.log(myName.charAt(1) == 'Z');
console.log("(2+3)==6 ? | Predict False.");
console.log((2 + 3) == 6);
console.log("(4+3)==7 ? | Predict True.");
console.log((4 + 3) == 7);
console.log("(1+5)>9 ? | Predict False.");
console.log((1 + 5) > 9);
console.log("3<9 ? | Predict True.");
console.log(3 < 9);
console.log("myName.charAt(0)=='M' ? | Predict True.");
console.log(myName.charAt(0) == 'M');
console.log("myName!='Malik' ? | Predict False.");
console.log(myName != "Malik");
